travis:
  secure:
    BINSTAR_TOKEN: gAycy1KwO+HXFAxS7Pq8alR0vRI58P/REGuzHS85I0iyR8XG2M7hY82faaHRkfFxOC/UsQg3ZBbMHOtDTK+N0q40/fCfeVTeApuyGXBLSeqZw4qmhnFg4X1joqdKZFahj9fTBhfPP45462aYDVfrDMAbdxU400xqWgZ/dZ+1LC2kPxmSsnY9Mw8VvJuTj9wavLnIhAFjX4e7oK3qD6OYLQ16YGdURWWUqF4sc34QR/7juF202gsEpA4dIeU/FQiHG9++CaFL4EZOByvJhRyWoRMcqYknYTnPzpTUbO9ePU5jXAe1uX5HzYWXEiYdEI4EFssf6Zn0qvHEdziz99V3klF5L37dtAmCgjT3npRuVllfyIbo83X7RORpZkVoTAGvDu5jaGheHTeXZzIPFAKI/4WUGn+tz6sdIEGrch/4LimHOsLSHzYlzP3JjHSsGC4AHCXwNiONsgx2dmX/v8iHW1jGnRaqrb2LGE267YKbtqvTZJPs3BQtV9kz5J/lrkty8AfAyu/YxiH5Pt/LyklrW8ob3/EKc/ljvA6GESjJkgaWoO3y96+pi/6QfHskK0sLguei91RGPt5Ja7RkqhaBJ5OI1GTCWrbHzOiiAP5YGfAUP8Zmtq5mwIGrM+fQUafWYQMQd0Bv5yb+5OEcNZKUuyWYYoeSb0rImteDT87UVxU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
