travis:
  secure:
    BINSTAR_TOKEN: wj4Fs9A/KOA3tQ2U1vKcsPELeY3epguNb0SwvPqZvL6Fn7Dim7Jj0H47MzlClVYdbjwoBC6C5SvM1dyK1gbDtslHv0aW499NqiSGCd6bMhFjP+evvH9UM6ofmqE2XJb/fEhu8999ZSrRfzGoCBAveu4D6TBnfkc0bGrMd2KkreimU+kWCz6GD+k9+E6p6wF7+jE6DyKvQb5zyh5A42LT2ZJIwXqBz17F9cJPUgOb97l89e4mf0s+nWTjXQ8cH9HmpitIkOFLnc9X3MDpsX2Ky9ERDGllYFPSCLKc46rcWUverIZ/vwWyGEc1c7M5NcbiR5bkVVEtOG7Q+P9Xv52KqX+S8qvDcB/zbqM1cwgWOLwh+vOmiWTSYFM39rXen0lYYDUNTibnj1PeLUMHYML2Cz9VkOpj17E9fqiBzqNReX9/x+TgCBI4fhExD4AQK8uiP4r0TUZgGcJHorCvqZs/Ajz6/uuzAmDuz7wrQD9LILt9RX6Ep2Yz7CXoZRG94o3Nq+olSYgp1PcFKDygMesi01ACYZBdt3UHgsJYzIf4qVUjpl/+deYLWUPwK1ZYqPnwNfV5JGOK6cmvAKBwYnnpsOKMPgveu2H/0jVuWijGiwNAwtk9Q2/DuPN3FBHhHdTvH19Yfw0Oi4szqVvoIyLvjJLLrHvacMkgNyTMCqXuiWw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
