travis:
  secure:
    BINSTAR_TOKEN: ezztJ44YYWyVXh4sy8/VWkq4Ak3u4y5hrvOMCV/i9ai1dZXW5gkujkVkgB3DunfbN76CFLzq5JSF71Wv92x6SDdbiOKSCZiIeOJ0pZR+tCiuAR6YCvzdjJjlvCDTWp0z+aXQKg7WfStQO/kVcRpjmjG2p6X82ZlEVgqE8Bgcg844sk3Ht2p7XRhvu2iEkm/IfxIkYuDw5g8QYiOtgScLz5NWlaoIWtXnAJ1D4JciuhdNZDBwt4TzI9Sch8PbsdDmE61CsWtbyUuWJDofwvhnlUdnHO/7jjdHTIhwqK92+GSJq/KSGDfF82ep0/t9W2fcN2cMdKG46X7vhLd1MeS95OcuKUTWfxe/0tOvFU6mwm9F9j7XZqkEcwDLEdrNFg/w4N4DMKv8t3gimNleSMfcoXsyyNC0RHvTSk9E5BJMH/fv+2iFEAgE1/b9AKesRwOGj+KgT37AxwMkT854lWDJqMH5uKsK0Celg43A2on2mkn6r+9TzUK7n16DXnGtDINi9tsXCyjJ+j1utPMZA6CkdDsVj9PUDT0D2m6Hmkta2Ij1bkv/KlBLvU04AofUoHjv803HT0wqK9WdGgIz+Mzvseb/BDzgvj/bdKl+xaWpFNH95ioWtukufYSrCDb4w7jCY2pmJpY5SJJAgBvJxDkpSMi/iGpWApiQL4I6Jwid/pU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
